orbs:
  gcp-cli: circleci/gcp-cli@1.0.0
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          executor: gcp-cli/default